name: Auto Post Every 30 Minutes

on:
  schedule:
    # Run every 30 minutes
    - cron: "*/30 * * * *"
  workflow_dispatch:
    inputs:
      debug:
        description: "Run in debug mode"
        required: false
        type: boolean
        default: false

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Auto Post
        env:
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: python AutomaticPoster.py
